import MovieCard from "@/components/MovieCard";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import Image from "next/image";
import useSwr from "swr";

const fetcher = (url) => fetch(url).then((res) => res.json());

export default function MoviesPage({}) {
  const router = useRouter();
  const { data } = useSwr(
    router.query.id ? `/api/hello?id=${router.query.id}` : null,
    fetcher
  );
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-6">
        {data && <MovieCard {...data} />}
        <pre>{JSON.stringify(data, null, 2)}</pre>
      </main>

      <footer className="">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
