import SearchInput from "../components/SearchInput";
import Head from "next/head";
import Image from "next/image";

import MovieCardList from "../components/MovieCardList";

const HomeContainer = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <SearchInput />
        {/* <MovieCardList inputData={value} /> */}
      </main>

      <footer className="">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default function Home({ fallback }) {
  return <HomeContainer />;
}
