import Head from "next/head";
import Image from "next/image";
import useSWR, { SWRConfig } from "swr";

export async function getStaticProps() {
  // `getStaticProps` is executed on the server side.

  return {
    props: {
      fallback: {
        "/api/hello": { name: "potomadre" },
      },
    },
  };
}

const HomeContainer = () => {
  const { data } = useSWR("/api/hello");

  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1>{data.name}</h1>
      </main>

      <footer className="">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default function Home({ fallback }) {
  return (
    <SWRConfig
      value={{
        fallback,
        refreshInterval: 3000,
        fetcher: (resource, init) =>
          fetch(resource, init).then((res) => res.json()),
      }}
    >
      <HomeContainer />
    </SWRConfig>
  );
}
