export const normalMovie = {
  Title: "Batman",
  Year: "1989",
  Rated: "PG-13",
  Released: "23 Jun 1989",
  Runtime: "126 min",
  Genre: "Action, Adventure",
  Director: "Tim Burton",
  Writer: "Bob Kane, Sam Hamm, Warren Skaaren",
  Actors: "Michael Keaton, Jack Nicholson, Kim Basinger",
  Plot: "The Dark Knight of Gotham City begins his war on crime with his first major enemy being Jack Napier, a criminal who becomes the clownishly homicidal Joker.",
  Language: "English, French, Spanish",
  Country: "United States, United Kingdom",
  Awards: "Won 1 Oscar. 9 wins & 26 nominations total",
  Poster:
    "https://m.media-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg",
  Ratings: [
    { Source: "Internet Movie Database", Value: "7.5/10" },
    { Source: "Rotten Tomatoes", Value: "71%" },
    { Source: "Metacritic", Value: "69/100" },
  ],
  Metascore: "69",
  imdbRating: "7.5",
  imdbVotes: "350,141",
  imdbID: "tt0096895",
  Type: "movie",
  DVD: "22 Aug 1997",
  BoxOffice: "$251,348,343",
  Production:
    "Warner Brothers, PolyGram Filmed Entertainment, Guber-Peters Company",
  Website: "N/A",
  Response: "True",
};

export const movieWithoutPlot = {
  Title: "Johnny Stecchino",
  Year: "1991",
  Rated: "R",
  Released: "24 Oct 1991",
  Runtime: "102 min",
  Genre: "Comedy, Crime, Romance",
  Director: "Roberto Benigni",
  Writer: "Roberto Benigni, Vincenzo Cerami",
  Actors: "Roberto Benigni, Nicoletta Braschi, Paolo Bonacelli",
  Plot: "",
  Language: "Italian",
  Country: "Italy",
  Awards: "5 wins & 3 nominations",
  Poster:
    "https://m.media-amazon.com/images/M/MV5BZjU0MGNkYWUtMzkxMS00NWU4LWI5NjEtYTZkNWUyOTdiMzQwXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg",
  Ratings: [
    { Source: "Internet Movie Database", Value: "7.2/10" },
    { Source: "Rotten Tomatoes", Value: "46%" },
  ],
  Metascore: "N/A",
  imdbRating: "7.2",
  imdbVotes: "10,362",
  imdbID: "tt0102164",
  Type: "movie",
  DVD: "N/A",
  BoxOffice: "$626,057",
  Production:
    "Silvio Berlusconi Communications, Cecchi Gori Group Tiger Cinema",
  Website: "N/A",
  Response: "True",
};
